### ISSUE TITLE
only right view is visible.

### ISSUE THREAD

**Issue by wisher01** [ChristianIngwersen/SportsPose#2]
Hello. Mr. Chrstian.
It's an honor to be the first issuer of this great work.

I've checked the data that you shared and It was ok for the 'right' view.
but it seems the data contains only the right direction.

when I changed arguments in SportsPoseDataset function, and I got KeyError for arguing that there is no key for 'left' or 'front'
here's the screen shot.
![image](https://user-images.githubusercontent.com/127624363/232732742-58a7cd8a-520a-4182-8ef4-415cabb6f17e.png)

Thank you for great work of you team and sorry if I missed something very simple.

**Comment by ChristianIngwersen** [comment]
Hi @wisher01, 

It is correct that only the right view is released at the moment. We are encouraging people to focus on research in monocular pose estimation, but will also release all of the views later.

**Comment by qbxlvnf11** [comment]
@ChristianIngwersen Are there any plans to provide other views at the moment? Thank you for providing good data. :)
