### ISSUE TITLE
Bounding boxes

### ISSUE THREAD

**Issue by RJaikanth** [ChristianIngwersen/SportsPose#4]
Hi,

Are bounding boxes for each subject provided in the data?

**Comment by ChristianIngwersen** [comment]
Hi @RJaikanth 

No not directly, but it should be easy to derive a tight bbox based on the reprojected 2D joints :-)

**Comment by RJaikanth** [comment]
Hi @ChristianIngwersen 

Follow up question - 
If we sample the dataset using sample_level="frame", how to get the frame number for each output. This is because I want to grab every 5th frame only (Vid1-Frame0, Vid1-Frame5 etc.)

**Comment by ChristianIngwersen** [comment]
Hi @RJaikanth,

This is what the `sample_method` is made for :-) 

```
        sample_level (str): The level to sample from the dataset. Must be one of the following:
            (string) "frame": Sample based on the frames.
            (string) "video": Sample from the videos. In this case "sample_method" can be provided,
                                otherwise uniform over frames is used.
        sample_method (callable): A callable to sample from the dataset. If None, the default sampling method is used.
```
https://github.com/ChristianIngwersen/SportsPose/blob/7f83c4f96b8e7c582fd8442d67c8b57afb89a1d7/src/sportspose/dataset.py#L309

**Comment by RJaikanth** [comment]
@ChristianIngwersen 

I am a bit confused on how this method works. From my understanding, this can be used only when `sample_level=video` and can output only a single frame for each video. However, I want every 5th frame from each video. 

Edit: By every 5th frame I mean for Vid0, I extract Frame0, Frame4, Frame9, and so on...

Please let me know if I am understanding this incorrectly. The code at  given below suggests the same. 

https://github.com/ChristianIngwersen/SportsPose/blob/7f83c4f96b8e7c582fd8442d67c8b57afb89a1d7/src/sportspose/dataset.py#L1003-L1020

https://github.com/ChristianIngwersen/SportsPose/blob/7f83c4f96b8e7c582fd8442d67c8b57afb89a1d7/src/sportspose/dataset.py#L1097-L1100

**Comment by RJaikanth** [comment]
Wrapped it around another class that kept track of video id and frame number to extract the frames required.
