### ISSUE TITLE
Getting data into COCO-format

### ISSUE THREAD

**Issue by axelssons** [ChristianIngwersen/SportsPose#6]
Hi!

Thanks for the great work on SportsPose. Do you know how one would go about implementing this dataset in MMPose for 3D pose estimation using i.e. MotionBert?

Best regards,
Jonathan

**Comment by ChristianIngwersen** [comment]
Hi Jonathan,

You can see this for inspiration:
https://github.com/ChristianIngwersen/MotionBERT-SportsPose/blob/02ca1cb415d773e470fa27cc69d44e98fd238b2c/train_sportspose.py#L267

You might however need to change the dataset definition provided here.
